import Vue from 'vue'
import VueRouter from 'vue-router'




Vue.use(VueRouter)

const routes = [
  {
    path: '/Login',
    name: 'Login',
    component: () => import('../views/Login.vue'),
  },
  {
    path: '/Main',
    name: 'Main',
    component: () => import('../views/Main.vue'),
    children:[
      {
        path:'/Notice',
        name:'Notice',
        meta:{
          title:'新闻公告'
        },
        component:()=>import('../views/Notice/Notice.vue'),
      },
      {
        path:'/Notice_Detail',
        name:'Notice_Detail',
        meta:{
          title:'新闻公告详情'
        },
        component:()=>import('../views/Notice/Notice_Detail.vue'),
      },
      {
        path:'/Notice_DetailManage',
        name:'Notice_DetailManage',
        meta:{
          title:'新闻公告详情管理'
        },
        component:()=>import('../views/Notice/Notice_DetailManage.vue'),
      },
      {
        path:'/Notice_Manage',
        name:'Notice_Manage',
        meta:{
          title:'新闻公告管理'
        },
        component:()=>import('../views/Notice/Notice_Manage.vue'),
      },{
        path:'/Personal_Detail',
        name:'Personal_Detail',
        meta:{
          title:'个人中心'
        },
        component:()=>import('../views/Personal_Detail.vue'),
      },
      {
        path:'/User_Manage',
        name:'User_Manage',
        meta:{
          title:'用户管理'
        },
        component:()=>import('../views/User/User_Manage.vue'),
      },
      {
        path:'/Student_GradeByCourseManage',
        name:'Student_GradeByCourseManage',
        meta:{
          title:'学生成绩管理（课程界面）'
        },
        component:()=>import('../views/User/Student_GradeByCourseManage.vue'),
      },
      {
        path:'/Class_Manage',
        name:'Class_Manage',
        meta:{
          title:'班级管理'
        },
        component:()=>import('../views/Class/Class_Manage.vue'),
      },
      {
        path:'/Class_UserManage',
        name:'Class_UserManage',
        meta:{
          title:'班级成员管理'
        },
        component:()=>import('../views/Class/Class_UserManage.vue'),
      },{
        path:'/Course_Manage',
        name:'Course_Manage',
        meta:{
          title:'课程管理'
        },
        component:()=>import('../views/Course/Course_Manage.vue'),
      },{
        path:'/Course_LabManage',
        name:'Course_LabManage',
        meta:{
          title:'课程实验室安排'
        },
        component:()=>import('../views/Course/Course_LabManage.vue'),
      },{
        path:'/Course_GradeManage',
        name:'Course_GradeManage',
        meta:{
          title:'课程课程安排'
        },
        component:()=>import('../views/Course/Course_GradeManage.vue'),
      },{
        path:'/TrainingPlan_Manage',
        name:'TrainingPlan_Manage',
        meta:{
          title:'实训计划管理'
        },
        component:()=>import('../views/TrainingPlan/TrainingPlan_Manage.vue'),
      },
      {
        path:'/TrainingPlan_ClassManage',
        name:'TrainingPlan_ClassManage',
        meta:{
          title:'实训计划参与班级管理'
        },
        component:()=>import('../views/TrainingPlan/TrainingPlan_ClassManage.vue'),
      },
      {
        path:'/Equipment_Manage',
        name:'Equipment_Manage',
        meta:{
          title:'设备管理'
        },
        component:()=>import('../views/Equipment/Equipment_Manage.vue'),
      },
      {
        path:'/Lab_Manage',
        name:'Lab_Manage',
        meta:{
          title:'设备管理'
        },
        component:()=>import('../views/Lab/Lab_Manage.vue'),
      },
      {
        path:'/Course_GradeByStu',
        name:'Course_GradeByStu',
        meta:{
          title:'学生课程成绩查询'
        },
        component:()=>import('../views/Course/Course_GradeByStu.vue'),
      },
      {
        path:'/Course_LabByStu',
        name:'Course_LabByStu',
        meta:{
          title:'学生课程实验室安排'
        },
        component:()=>import('../views/Course/Course_LabByStu.vue'),
      },
      {
        path:'/Class_StuUser',
        name:'Class_StuUser',
        meta:{
          title:'查看我的班级'
        },
        component:()=>import('../views/Class/Class_StuUser.vue'),
      },
      {
        path:'/TrainingPlan_ClassStu',
        name:'TrainingPlan_ClassStu',
        meta:{
          title:'查看我的实训'
        },
        component:()=>import('../views/TrainingPlan/TrainingPlan_ClassStu.vue'),
      },
      {
        path:'/Class_TeacherUser',
        name:'Class_TeacherUser',
        meta:{
          title:'查看班级'
        },
        component:()=>import('../views/Class/Class_TeacherUser.vue'),
      },
      {
        path:'/Class_TeacherUserManger',
        name:'Class_TeacherUserManger',
        meta:{
          title:'查看班级'
        },
        component:()=>import('../views/Class/Class_TeacherUserManger.vue'),
      },
      {
        path:'/Class_TeacherProUser',
        name:'Class_TeacherProUser',
        meta:{
          title:'查看班级'
        },
        component:()=>import('../views/Class/Class_TeacherProUser.vue'),
      },
      {
        path:'/TrainingPlan_ClassTeacher',
        name:'TrainingPlan_ClassTeacher',
        meta:{
          title:'查看实训'
        },
        component:()=>import('../views/TrainingPlan/TrainingPlan_ClassTeacher.vue'),
      },
      {
        path:'/TrainingPlan_TeacherManage',
        name:'TrainingPlan_TeacherManage',
        meta:{
          title:'查看实训'
        },
        component:()=>import('../views/TrainingPlan/TrainingPlan_TeacherManage.vue'),
      },
      {
        path:'/Course_TeacherManage',
        name:'Course_TeacherManage',
        meta:{
          title:'管理课程'
        },
        component:()=>import('../views/Course/Course_TeacherManage.vue'),
      },
      {
        path:'/Teacher_GradeByCourseManage',
        name:'Teacher_GradeByCourseManage',
        meta:{
          title:'成绩管理'
        },
        component:()=>import('../views/Course/Teacher_GradeByCourseManage.vue'),
      },
      {
        path:'/Cause_TeacherLabManage',
        name:'Cause_TeacherLabManage',
        meta:{
          title:'成绩管理'
        },
        component:()=>import('../views/Course/Cause_TeacherLabManage.vue'),
      },
      {
        path:'/Class_TeacherProUserManage',
        name:'Class_TeacherProUserManage',
        meta:{
          title:'学生管理'
        },
        component:()=>import('../views/Class/Class_TeacherProUserManage.vue'),
      },
      {
        path:'/TeacherPro_GradeByCourseManage',
        name:'TeacherPro_GradeByCourseManage',
        meta:{
          title:'学生成绩查看'
        },
        component:()=>import('../views/Course/TeacherPro_GradeByCourseManage.vue'),
      },
      {
        path:'/Course_TeacherProManage',
        name:'Course_TeacherProManage',
        meta:{
          title:'学生成绩查看'
        },
        component:()=>import('../views/Course/Course_TeacherProManage.vue'),
      },
    ]
  }

]

const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes
})

export default router